apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: sentiment-analysis-function
spec:
  className: io.streamnative.functions.ml.SentimentAnalysisFunction
  forwardSourceMessageProperty: true
  maxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 5
  image: localhost:32000/sentiment-analysis-function:1.0.0
  logTopic: persistent://public/default/logging-function-logs
  input:
    topics:
      - persistent://public/default/tweet-input-topic
    typeClassName: java.lang.String
  output:
    topic: persistent://public/default/tweet-output-topic
    typeClassName: java.lang.String
  resources:
    requests:
      cpu: "0.1"
      memory: 1G
    limits:
      cpu: "0.2"
      memory: 1.1G
  pulsar:
    pulsarConfig: "pulsar"
  volumeMounts:
    - mountPath: /cache
      name: cache-volume
  pod:
    env:
      - name: EXAMPLE_VARIABLE
        value: exampleValue
    labels:
      "location": "mtv"
    annotations:
      "managed-function": "true"
    volumes:
      - name: cache-volume
        emptyDir: {}
    imagePullSecrets:
      - name: regcred
    initContainers:
      - name: init-function
        image: busybox:1.28
        command: ['sh', '-c', 'echo The app is running! && sleep 30']
    sidecars:
      - name: sidecar-function
        image: busybox:1.28
        command: ['sh', '-c', 'echo The app is running! && sleep 30000']
  java:
    jar: /pulsar/sentiment-analysis-function-1.0.0.jar
    # use "" to read jar from local file system
    jarLocation: ""
  clusterName: test-pulsar
  autoAck: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar
data:
  webServiceURL: http://10.152.183.143:8080
  brokerServiceURL: pulsar://10.152.183.143:6650