version: '3.9'

services:

  pulsar:
    container_name: pulsar
    hostname: pulsar
    image: streamnative/sn-pulsar:2.9.3.4
    volumes:
      - /Users/david/clone-zone/personal/sentiment-analysis/tweet-simulator/target:/tweetSource
      - /Users/david/clone-zone/personal/sentiment-analysis/sentiment-analysis-function/target:/functionSource
    command: >
      bash -c "bin/apply-config-from-env.py conf/standalone.conf &&
      exec bin/pulsar standalone -nss" # disable stream storage and functions worker
    environment:
      allowAutoTopicCreationType: partitioned
      brokerDeleteInactiveTopicsEnabled: "false"
      PULSAR_PREFIX_functionsWorkerEnabled: "true"
      PULSAR_PREFIX_webServicePort: 8080
    ports:
      - 6650:6650
      - 8080:8080

networks:
  default:
    name: sentiment-analysis